import axios from "axios";
import { createContext, useEffect, useState } from "react";

export const ClothesDataContext = createContext();

export const ClothesDataContextProvider = ({ children }) => {
  const [loader, setLoader] = useState(true);

  // const [data, setData] = useState([
  //   {
  //     id: 1,
  //     name: "Seller_0",
  //     surname: "Wiegand",
  //     email: "nbayer@hotmail.com",
  //     phone: "904.875.4361",
  //     is_email_verified: "0",
  //     card_number: "8600572984398150",
  //     status: "approved",
  //     status_reason: null,
  //     seller_type_id: "3",
  //     region_id: "3",
  //     sub_region_id: "37",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 1,
  //         name: "Mr. Casey Harvey DVM",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Nike.svg.png",
  //         url_background_photo: null,
  //         status: "approved",
  //         status_reason: null,
  //         gender_id: "1",
  //         delivery_id: "2",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "1",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 1,
  //             name_uz: "product_name_1",
  //             name_ru: "product_name_1",
  //             gender_id: "2",
  //             min_age_category: "17",
  //             max_age_category: "92",
  //             sku: "154-176",
  //             description_uz: "exercitationem",
  //             description_ru: "dolores",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "approved",
  //             status_reason: "ddd",
  //             overall_rating: "5.0",
  //             rated_users_count: "119",
  //             producer_id: "6",
  //             category_id: "1",
  //             type_id: "1",
  //             brand_id: "18",
  //             shop_id: "1",
  //             seller_id: "1",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 1,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/t-shirt.webp",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "1",
  //                 product_color_id: "1",
  //                 created_at: "2024-01-23T07:03:54.000000Z",
  //                 updated_at: "2024-01-23T07:03:54.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "1",
  //               price: "256397",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 1,
  //               category_id: "1",
  //               name_uz: "Kepka",
  //               name_ru: "Кепка",
  //             },
  //           },
  //           {
  //             id: 12,
  //             name_uz: "product_name_12",
  //             name_ru: "product_name_12",
  //             gender_id: "2",
  //             min_age_category: "20",
  //             max_age_category: "110",
  //             sku: "450-273",
  //             description_uz: "sed",
  //             description_ru: "delectus",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "declined",
  //             status_reason: null,
  //             overall_rating: "3.0",
  //             rated_users_count: "194",
  //             producer_id: "7",
  //             category_id: "2",
  //             type_id: "9",
  //             brand_id: "27",
  //             shop_id: "1",
  //             seller_id: "1",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 12,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/sport.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "12",
  //                 product_color_id: "12",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "12",
  //               price: "695485",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 9,
  //               category_id: "2",
  //               name_uz: "Futbolka",
  //               name_ru: "Футболка",
  //             },
  //           },
  //           {
  //             id: 120,
  //             name_uz: "product_name_12",
  //             name_ru: "product_name_120",
  //             gender_id: "2",
  //             min_age_category: "20",
  //             max_age_category: "110",
  //             sku: "450-273",
  //             description_uz: "sed",
  //             description_ru: "delectus",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "declined",
  //             status_reason: null,
  //             overall_rating: "3.0",
  //             rated_users_count: "194",
  //             producer_id: "7",
  //             category_id: "2",
  //             type_id: "9",
  //             brand_id: "27",
  //             shop_id: "1",
  //             seller_id: "1",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 12,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/sport.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "12",
  //                 product_color_id: "12",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "12",
  //               price: "695485",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 9,
  //               category_id: "2",
  //               name_uz: "Futbolka",
  //               name_ru: "Футболка",
  //             },
  //           },
  //         ],
  //       },
  //       {
  //         id: 13,
  //         name: "Dr. Priscilla Feest PhD",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/The_North_Face.svg.png",
  //         url_background_photo: null,
  //         status: "approved",
  //         status_reason: null,
  //         gender_id: "3",
  //         delivery_id: "2",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "1",
  //         created_at: null,
  //         updated_at: null,
  //         products: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 2,
  //     name: "Seller_1",
  //     surname: "Prosacco",
  //     email: "edmund.frami@rowe.biz",
  //     phone: "1-820-445-5673",
  //     is_email_verified: "0",
  //     card_number: "8600572984398151",
  //     status: "approved",
  //     status_reason: null,
  //     seller_type_id: "1",
  //     region_id: "13",
  //     sub_region_id: "149",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 2,
  //         name: "Toby Nader",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Tiffany.svg.png",
  //         url_background_photo: null,
  //         status: "approved",
  //         status_reason: null,
  //         gender_id: "2",
  //         delivery_id: "1",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "2",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 2,
  //             name_uz: "product_name_2",
  //             name_ru: "product_name_2",
  //             gender_id: "2",
  //             min_age_category: "5",
  //             max_age_category: "125",
  //             sku: "854-248",
  //             description_uz: "voluptatem",
  //             description_ru: "dignissimos",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "updated",
  //             status_reason: null,
  //             overall_rating: "2.0",
  //             rated_users_count: "34",
  //             producer_id: "13",
  //             category_id: "5",
  //             type_id: "68",
  //             brand_id: "11",
  //             shop_id: "2",
  //             seller_id: "2",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 2,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/sneakers.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "2",
  //                 product_color_id: "2",
  //                 created_at: "2024-01-23T07:03:54.000000Z",
  //                 updated_at: "2024-01-23T07:03:54.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "2",
  //               price: "70913",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 68,
  //               category_id: "5",
  //               name_uz: "Bo'yin taqinchoqlari",
  //               name_ru: "Шейные украшения",
  //             },
  //           },
  //           {
  //             id: 11,
  //             name_uz: "product_name_11",
  //             name_ru: "product_name_11",
  //             gender_id: "2",
  //             min_age_category: "19",
  //             max_age_category: "40",
  //             sku: "739-302",
  //             description_uz: "voluptatem",
  //             description_ru: "sint",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "updated",
  //             status_reason: null,
  //             overall_rating: "5.0",
  //             rated_users_count: "176",
  //             producer_id: "6",
  //             category_id: "1",
  //             type_id: "1",
  //             brand_id: "10",
  //             shop_id: "2",
  //             seller_id: "2",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 11,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/street.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "11",
  //                 product_color_id: "11",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "11",
  //               price: "240491",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 1,
  //               category_id: "1",
  //               name_uz: "Kepka",
  //               name_ru: "Кепка",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     id: 3,
  //     name: "Seller_2",
  //     surname: "Lowe",
  //     email: "willms.christina@gmail.com",
  //     phone: "+18704320479",
  //     is_email_verified: "0",
  //     card_number: "8600572984398152",
  //     status: "approved",
  //     status_reason: null,
  //     seller_type_id: "5",
  //     region_id: "6",
  //     sub_region_id: "139",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 3,
  //         name: "Daisy Bogisich IV",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Coach.svg.png",
  //         url_background_photo: null,
  //         status: "approved",
  //         status_reason: null,
  //         gender_id: "1",
  //         delivery_id: "1",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "3",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 3,
  //             name_uz: "product_name_3",
  //             name_ru: "product_name_107",
  //             gender_id: "2",
  //             min_age_category: "11",
  //             max_age_category: "66",
  //             sku: "585-879",
  //             description_uz: "nostrum",
  //             description_ru: "eius",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "updated",
  //             status_reason: null,
  //             overall_rating: "4.0",
  //             rated_users_count: "186",
  //             producer_id: "10",
  //             category_id: "5",
  //             type_id: "68",
  //             brand_id: "2",
  //             shop_id: "3",
  //             seller_id: "3",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 3,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/ronaldo.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "3",
  //                 product_color_id: "3",
  //                 created_at: "2024-01-23T07:03:54.000000Z",
  //                 updated_at: "2024-01-23T07:03:54.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "3",
  //               price: "809068",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 68,
  //               category_id: "5",
  //               name_uz: "Bo'yin taqinchoqlari",
  //               name_ru: "Шейные украшения",
  //             },
  //           },
  //           {
  //             id: 106,
  //             name_uz: "product_name_3",
  //             name_ru: "product_name_106",
  //             gender_id: "2",
  //             min_age_category: "11",
  //             max_age_category: "66",
  //             sku: "585-879",
  //             description_uz: "nostrum",
  //             description_ru: "eius",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "approved",
  //             status_reason: null,
  //             overall_rating: "4.0",
  //             rated_users_count: "186",
  //             producer_id: "10",
  //             category_id: "5",
  //             type_id: "68",
  //             brand_id: "2",
  //             shop_id: "3",
  //             seller_id: "3",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 3,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/ronaldo.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "3",
  //                 product_color_id: "3",
  //                 created_at: "2024-01-23T07:03:54.000000Z",
  //                 updated_at: "2024-01-23T07:03:54.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "3",
  //               price: "809068",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 68,
  //               category_id: "5",
  //               name_uz: "Bo'yin taqinchoqlari",
  //               name_ru: "Шейные украшения",
  //             },
  //           },
  //           {
  //             id: 105,
  //             name_uz: "product_name_3",
  //             name_ru: "product_name_105",
  //             gender_id: "2",
  //             min_age_category: "11",
  //             max_age_category: "66",
  //             sku: "585-879",
  //             description_uz: "nostrum",
  //             description_ru: "eius",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "approved",
  //             status_reason: null,
  //             overall_rating: "4.0",
  //             rated_users_count: "186",
  //             producer_id: "10",
  //             category_id: "5",
  //             type_id: "68",
  //             brand_id: "2",
  //             shop_id: "3",
  //             seller_id: "3",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 3,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/ronaldo.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "3",
  //                 product_color_id: "3",
  //                 created_at: "2024-01-23T07:03:54.000000Z",
  //                 updated_at: "2024-01-23T07:03:54.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "3",
  //               price: "809068",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 68,
  //               category_id: "5",
  //               name_uz: "Bo'yin taqinchoqlari",
  //               name_ru: "Шейные украшения",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     id: 4,
  //     name: "Seller_3",
  //     surname: "Doyle",
  //     email: "vena68@klein.com",
  //     phone: "+16895268092",
  //     is_email_verified: "0",
  //     card_number: "8600572984398153",
  //     status: "approved",
  //     status_reason: null,
  //     seller_type_id: "7",
  //     region_id: "5",
  //     sub_region_id: "162",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 4,
  //         name: "Prof. Dorian Bernhard",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/The_North_Face.svg.png",
  //         url_background_photo: null,
  //         status: "approved",
  //         status_reason: null,
  //         gender_id: "1",
  //         delivery_id: "2",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "4",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 4,
  //             name_uz: "product_name_4",
  //             name_ru: "product_name_4",
  //             gender_id: "2",
  //             min_age_category: "6",
  //             max_age_category: "75",
  //             sku: "626-736",
  //             description_uz: "facere",
  //             description_ru: "nam",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "approved",
  //             status_reason: null,
  //             overall_rating: "2.0",
  //             rated_users_count: "156",
  //             producer_id: "6",
  //             category_id: "1",
  //             type_id: "1",
  //             brand_id: "25",
  //             shop_id: "4",
  //             seller_id: "4",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 4,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/eminem.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "4",
  //                 product_color_id: "4",
  //                 created_at: "2024-01-23T07:03:54.000000Z",
  //                 updated_at: "2024-01-23T07:03:54.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "4",
  //               price: "196730",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 1,
  //               category_id: "1",
  //               name_uz: "Kepka",
  //               name_ru: "Кепка",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     id: 5,
  //     name: "Seller_4",
  //     surname: "Dickens",
  //     email: "ycarroll@grant.com",
  //     phone: "(980) 982-1974",
  //     is_email_verified: "0",
  //     card_number: "8600572984398154",
  //     status: "declined",
  //     status_reason: null,
  //     seller_type_id: "8",
  //     region_id: "6",
  //     sub_region_id: "127",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 5,
  //         name: "Fred Monahan",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Skechers.jpg",
  //         url_background_photo: null,
  //         status: "declined",
  //         status_reason: null,
  //         gender_id: "1",
  //         delivery_id: "2",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "5",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 5,
  //             name_uz: "product_name_5",
  //             name_ru: "product_name_5",
  //             gender_id: "1",
  //             min_age_category: "30",
  //             max_age_category: "41",
  //             sku: "711-799",
  //             description_uz: "doloribus",
  //             description_ru: "voluptatum",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "declined",
  //             status_reason: null,
  //             overall_rating: "4.0",
  //             rated_users_count: "104",
  //             producer_id: "5",
  //             category_id: "1",
  //             type_id: "1",
  //             brand_id: "33",
  //             shop_id: "5",
  //             seller_id: "5",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 5,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/trousers.webp",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "5",
  //                 product_color_id: "5",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "5",
  //               price: "790249",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 1,
  //               category_id: "1",
  //               name_uz: "Kepka",
  //               name_ru: "Кепка",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     id: 6,
  //     name: "Seller_5",
  //     surname: "Bins",
  //     email: "lfranecki@emmerich.com",
  //     phone: "351.716.2338",
  //     is_email_verified: "0",
  //     card_number: "8600572984398155",
  //     status: "declined",
  //     status_reason: null,
  //     seller_type_id: "2",
  //     region_id: "12",
  //     sub_region_id: "126",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 6,
  //         name: "Alexandra Okuneva",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Tommy_Hilfiger.png",
  //         url_background_photo: null,
  //         status: "declined",
  //         status_reason: null,
  //         gender_id: "1",
  //         delivery_id: "2",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "6",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 6,
  //             name_uz: "product_name_6",
  //             name_ru: "product_name_6",
  //             gender_id: "2",
  //             min_age_category: "8",
  //             max_age_category: "102",
  //             sku: "673-677",
  //             description_uz: "vel",
  //             description_ru: "commodi",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "declined",
  //             status_reason: null,
  //             overall_rating: "3.0",
  //             rated_users_count: "115",
  //             producer_id: "8",
  //             category_id: "4",
  //             type_id: "56",
  //             brand_id: "46",
  //             shop_id: "6",
  //             seller_id: "6",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 6,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/shoes.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "6",
  //                 product_color_id: "6",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "6",
  //               price: "72180",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 56,
  //               category_id: "4",
  //               name_uz: "Aquasocks",
  //               name_ru: "Аквасоксы",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     id: 7,
  //     name: "Seller_6",
  //     surname: "Hill",
  //     email: "amya.turner@erdman.net",
  //     phone: "+1-270-761-5055",
  //     is_email_verified: "0",
  //     card_number: "8600572984398156",
  //     status: "declined",
  //     status_reason: null,
  //     seller_type_id: "3",
  //     region_id: "11",
  //     sub_region_id: "54",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 7,
  //         name: "Mr. Jacey Ward",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Under_armour.svg.png",
  //         url_background_photo: null,
  //         status: "declined",
  //         status_reason: null,
  //         gender_id: "2",
  //         delivery_id: "2",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "7",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 7,
  //             name_uz: "product_name_7",
  //             name_ru: "product_name_7",
  //             gender_id: "1",
  //             min_age_category: "26",
  //             max_age_category: "65",
  //             sku: "126-118",
  //             description_uz: "sunt",
  //             description_ru: "vel",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "declined",
  //             status_reason: null,
  //             overall_rating: "5.0",
  //             rated_users_count: "57",
  //             producer_id: "9",
  //             category_id: "4",
  //             type_id: "56",
  //             brand_id: "32",
  //             shop_id: "7",
  //             seller_id: "7",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 7,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/tshirt.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "7",
  //                 product_color_id: "7",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "7",
  //               price: "531677",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 56,
  //               category_id: "4",
  //               name_uz: "Aquasocks",
  //               name_ru: "Аквасоксы",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     id: 8,
  //     name: "Seller_7",
  //     surname: "Kertzmann",
  //     email: "bconn@mante.com",
  //     phone: "423-972-5776",
  //     is_email_verified: "0",
  //     card_number: "8600572984398157",
  //     status: "declined",
  //     status_reason: null,
  //     seller_type_id: "8",
  //     region_id: "9",
  //     sub_region_id: "38",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 8,
  //         name: "Margaret Kautzer III",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Michael_Kors.svg.png",
  //         url_background_photo: null,
  //         status: "declined",
  //         status_reason: null,
  //         gender_id: "3",
  //         delivery_id: "2",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "8",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 8,
  //             name_uz: "product_name_8",
  //             name_ru: "product_name_8",
  //             gender_id: "2",
  //             min_age_category: "5",
  //             max_age_category: "52",
  //             sku: "838-661",
  //             description_uz: "in",
  //             description_ru: "accusamus",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "declined",
  //             status_reason: null,
  //             overall_rating: "2.0",
  //             rated_users_count: "97",
  //             producer_id: "5",
  //             category_id: "1",
  //             type_id: "1",
  //             brand_id: "32",
  //             shop_id: "8",
  //             seller_id: "8",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 8,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/jacket.webp",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "8",
  //                 product_color_id: "8",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "8",
  //               price: "778385",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 1,
  //               category_id: "1",
  //               name_uz: "Kepka",
  //               name_ru: "Кепка",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     id: 9,
  //     name: "Seller_8",
  //     surname: "Sanford",
  //     email: "eduardo.greenfelder@corkery.biz",
  //     phone: "+1-484-663-8917",
  //     is_email_verified: "0",
  //     card_number: "8600572984398158",
  //     status: "updated",
  //     status_reason: null,
  //     seller_type_id: "4",
  //     region_id: "7",
  //     sub_region_id: "86",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 9,
  //         name: "Ramona Larson",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Old_Navy.svg.png",
  //         url_background_photo: null,
  //         status: "updated",
  //         status_reason: null,
  //         gender_id: "3",
  //         delivery_id: "1",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "9",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 9,
  //             name_uz: "product_name_9",
  //             name_ru: "product_name_9",
  //             gender_id: "2",
  //             min_age_category: "7",
  //             max_age_category: "114",
  //             sku: "837-225",
  //             description_uz: "sunt",
  //             description_ru: "quia",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "approved",
  //             status_reason: null,
  //             overall_rating: "2.0",
  //             rated_users_count: "77",
  //             producer_id: "12",
  //             category_id: "5",
  //             type_id: "68",
  //             brand_id: "4",
  //             shop_id: "9",
  //             seller_id: "9",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 9,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/dress.webp",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "9",
  //                 product_color_id: "9",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "9",
  //               price: "347154",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 68,
  //               category_id: "5",
  //               name_uz: "Bo'yin taqinchoqlari",
  //               name_ru: "Шейные украшения",
  //             },
  //           },
  //           {
  //             id: 100,
  //             name_uz: "product_name_100",
  //             name_ru: "product_name_100",
  //             gender_id: "2",
  //             min_age_category: "7",
  //             max_age_category: "114",
  //             sku: "837-225",
  //             description_uz: "sunt",
  //             description_ru: "quia",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "updated",
  //             status_reason: null,
  //             overall_rating: "2.0",
  //             rated_users_count: "77",
  //             producer_id: "12",
  //             category_id: "5",
  //             type_id: "68",
  //             brand_id: "4",
  //             shop_id: "9",
  //             seller_id: "9",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 9,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/dress.webp",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "9",
  //                 product_color_id: "9",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "9",
  //               price: "347154",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 68,
  //               category_id: "5",
  //               name_uz: "Bo'yin taqinchoqlari",
  //               name_ru: "Шейные украшения",
  //             },
  //           },
  //           {
  //             id: 101,
  //             name_uz: "product_name_100",
  //             name_ru: "product_name_101",
  //             gender_id: "2",
  //             min_age_category: "7",
  //             max_age_category: "114",
  //             sku: "837-225",
  //             description_uz: "sunt",
  //             description_ru: "quia",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "updated",
  //             status_reason: null,
  //             overall_rating: "2.0",
  //             rated_users_count: "77",
  //             producer_id: "12",
  //             category_id: "5",
  //             type_id: "68",
  //             brand_id: "4",
  //             shop_id: "9",
  //             seller_id: "9",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 9,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/dress.webp",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "9",
  //                 product_color_id: "9",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "9",
  //               price: "347154",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 68,
  //               category_id: "5",
  //               name_uz: "Bo'yin taqinchoqlari",
  //               name_ru: "Шейные украшения",
  //             },
  //           },
  //           {
  //             id: 110,
  //             name_uz: "product_name_100",
  //             name_ru: "product_name_110",
  //             gender_id: "2",
  //             min_age_category: "7",
  //             max_age_category: "114",
  //             sku: "837-225",
  //             description_uz: "sunt",
  //             description_ru: "quia",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "updated",
  //             status_reason: null,
  //             overall_rating: "2.0",
  //             rated_users_count: "77",
  //             producer_id: "12",
  //             category_id: "5",
  //             type_id: "68",
  //             brand_id: "4",
  //             shop_id: "9",
  //             seller_id: "9",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 9,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/dress.webp",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "9",
  //                 product_color_id: "9",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "9",
  //               price: "347154",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 68,
  //               category_id: "5",
  //               name_uz: "Bo'yin taqinchoqlari",
  //               name_ru: "Шейные украшения",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     id: 10,
  //     name: "Seller_9",
  //     surname: "VonRueden",
  //     email: "vlowe@hagenes.com",
  //     phone: "1-501-367-3442",
  //     is_email_verified: "0",
  //     card_number: "8600572984398159",
  //     status: "updated",
  //     status_reason: null,
  //     seller_type_id: "3",
  //     region_id: "2",
  //     sub_region_id: "84",
  //     email_verified_at: null,
  //     created_at: "23-01-2024",
  //     updated_at: "23-01-2024",
  //     shops: [
  //       {
  //         id: 10,
  //         name: "Percy Conn",
  //         url_logo_photo:
  //           "https://api.dressme.uz/storage/brandsLogo/Levis.svg.png",
  //         url_background_photo: null,
  //         status: "updated",
  //         status_reason: null,
  //         gender_id: "1",
  //         delivery_id: "1",
  //         overall_rating: null,
  //         rated_users_count: null,
  //         seller_id: "10",
  //         created_at: null,
  //         updated_at: null,
  //         products: [
  //           {
  //             id: 10,
  //             name_uz: "product_name_10",
  //             name_ru: "product_name_10",
  //             gender_id: "2",
  //             min_age_category: "12",
  //             max_age_category: "48",
  //             sku: "516-628",
  //             description_uz: "nostrum",
  //             description_ru: "ea",
  //             quality_uz: "Original",
  //             quality_ru: "Оригинал",
  //             composition_uz: "cotton 100%",
  //             composition_ru: "хлопок 100%",
  //             status: "updated",
  //             status_reason: null,
  //             overall_rating: "5.0",
  //             rated_users_count: "95",
  //             producer_id: "10",
  //             category_id: "4",
  //             type_id: "56",
  //             brand_id: "33",
  //             shop_id: "10",
  //             seller_id: "10",
  //             created_at: "23-01-2024",
  //             updated_at: "23-01-2024",
  //             photos: [
  //               {
  //                 id: 10,
  //                 url_photo:
  //                   "https://api.dressme.uz/storage/productPhotos/costume.jpeg",
  //                 status: "approved",
  //                 status_reason: null,
  //                 product_id: "10",
  //                 product_color_id: "10",
  //                 created_at: "2024-01-23T07:03:55.000000Z",
  //                 updated_at: "2024-01-23T07:03:55.000000Z",
  //               },
  //             ],
  //             cost: {
  //               product_id: "10",
  //               price: "484965",
  //               discount_price: null,
  //               discount_percent: null,
  //             },
  //             type: {
  //               id: 56,
  //               category_id: "4",
  //               name_uz: "Aquasocks",
  //               name_ru: "Аквасоксы",
  //             },
  //           },
  //         ],
  //       },
  //     ],
  //   },
  // ]);

  const [data, setData] = useState([]);

  const url = "https://api.dressme.uz";

  let token = sessionStorage.getItem("token");

  // setTimeout(() => {
  //   setLoader(false);
  // }, 5000);

  useEffect(() => {
    if (token) {
      axios(`${url}/api/admin/products`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }).then((d) => {
        setData(d?.data?.sellers_products?.data);
        setLoader(false);
      });
    }
  }, []);

  const reFetch = () => {
    axios(`${url}/api/admin/products`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    }).then((d) => {
      setData(d?.data?.sellers_products?.data);
    });
  };

  return (
    <ClothesDataContext.Provider
      value={[data, setData, reFetch, loader, setLoader]}
    >
      {children}
    </ClothesDataContext.Provider>
  );
};
